[package]
name = "bfs-drivers"
version = "0.1.0"
authors = ["Ludovic Galabru <ludovic@blockstack.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
primitives = { package = "bfs-primitives", path = "../primitives" }
